import './styles/index.scss';
import './status/status';
import './menu/menu';
import './pages/mainPage';
import './pages/pageCategory';
import './pages/statisticPage';
import './game/startGame';
import './statistics/sortStatistics';
import './game/difficultWords';
